"""create tables

Revision ID: 2f7fde94fdfd
Revises: 8619199129fb
Create Date: 2020-08-12 22:18:05.217121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7fde94fdfd'
down_revision = '8619199129fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
